### ISSUE TITLE
Add client-side search support

### ISSUE THREAD

**Issue by SoumayaMauthoorMOJ** [ministryofjustice/mkdocs-tech-docs-template#10]
https://www.mkdocs.org/dev-guide/themes/#search-and-themes

**Comment by FISHMANPET** [comment]
I'm working on something very similair to you - a customized version of mkdocs-material to be used with my orgs branding standards, and I too came across search not working.  If I figure out what's needed, I'll share it here as well.

**Comment by SoumayaMauthoorMOJ** [comment]
@FISHMANPET thanks but fixed it by updating mkdocs config:
```
plugins:
  - material/search
```
I should have closed the issue before my bad :-)

**Comment by FISHMANPET** [comment]
No problem, thanks!  I did that and it worked just fine :)
